# Site settings
description: A blog about tech stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mauricioandrades.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mauricio
user_description: Web Dev, Data Sleuth, Font Aficionado
user_title: ...
email: mod.and.op@gmail.com
twitter_username: MODandOP
github_username:  MauricioAndrades
disqus_username: mauricioandrades


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
# http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Mauricio Andrades
    url: /
    id: home
  - title: Tags
    url: /tags
    id: tags
  - title: About Me
    url: /about
    id: about
  - title: Resume
    url: /resume
    id: resume

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
